### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by SlickNutter** [int0h/npm-hddSpace#3]
I'm trying to pass the options object into hddSpace as such:
```typescript
 hddSpace({format: 'gb'}, (info: DriveInfo) => {
    resolve(info);
});
```

In your modules index.ts the following is thrown:

>  TypeError: Cannot read property 'toLowerCase' of undefined

In the documentation of the package it says:
> It's possible to pass option object as the first argument. Now the only supported opion is format which can be one of the following (case insesetive): **...**

What Am I doing wrong?

**Comment by int0h** [comment]
Hello! You seem to do everything just fine! I've tried to run your example and it works. 
This code works fine for me: 
```js 
var hddSpace = require('hdd-space');

hddSpace({ format: 'gb' }, function (info) {
    console.log(info);
});
```
Could you please run it as a separate app?

According to the whole code of a package that kind of mistake may occur if you misspell format name (`gb` in your example, and it's right and works in my case). If the provided code was modificated make sure that it's correct.

Please tell me if the separate test app works.

**Comment by SlickNutter** [comment]
It works now, I think there was a problem with the typescript compilation, it wouldn't come to compiling this code and then I would execute the old code.
Sorry for any inconveniences.
